apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: test-secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: test-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password | toString }}"
  data:
    - secretKey: password
      remoteRef:
        key: enterprise-eks-platform/test-secret
        property: password
