apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: enterprise-eks-platform
    argocd.argoproj.io/app-of-apps: "true"
spec:
  project: platform

  sources:
    - repoURL: "https://charts.jetstack.io"
      chart: cert-manager
      targetRevision: v1.14.5
      helm:
        valuesObject:
          installCRDs: true
          replicaCount: 1

    - repoURL: "https://github.com/yelved92/enterprise-eks-platform.git"
      targetRevision: feat/phase-4-argocd
      path: helm/cert-manager/templates
      directory:
        recurse: true

  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m